apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcp.a3gw.secretName" . }}
  labels:
    component: vcp-a3gw

type: Opaque
stringData:
  jwt_config.json: |
{{ .Files.Get "files/a3gw/conf/jwt_config.json" | indent 4 }}

  service_proxies_config.json: |
{{ .Files.Get "files/a3gw/conf/service_proxies_config.json" | indent 4 }}
