# mobily/vcp/httpd/Dockerfile.vcp.k8slocal
FROM httpd:alpine

RUN mkdir -p /usr/local/apache2/conf.d
COPY ./vcp/conf.d.k8s /usr/local/apache2/conf.d
COPY ./vcp/conf/httpd.conf /usr/local/apache2/conf/httpd.conf

# Copy CA (Certification Authority) Public Key
COPY ./vcp/openssl.prod/server.crt /usr/local/apache2/conf/server.crt
COPY ./vcp/openssl.prod/server.key /usr/local/apache2/conf/server.key
