# mobily/dsp/a3gw/Dockerfile.dsp.prod

FROM mersin.telenity.com/com/telenity/a3gw:1.0.9-main

WORKDIR /space/a3gw

COPY ./dsp/ecosystem.config.js ./ecosystem.config.js
COPY ./dsp/conf.prod ./src/conf
RUN mkdir -p ./static
COPY ./dsp/static.prod ./static

EXPOSE 8444
EXPOSE 8445
CMD ["pm2-runtime", "start", "ecosystem.config.js"]
