apiVersion: v1
kind: Service
metadata:
  name: consolportals-sa-stc-vcp-a3gw-service
  labels:
    app: consolportals-sa-stc-vcp
    component: vcp-a3gw
spec:
  type: ClusterIP
  selector:
    app: consolportals-sa-stc-vcp
    component: vcp-a3gw
  ports:
    - name: portals
      port: 8444
      targetPort: 8444
      protocol: TCP
    - name: auth
      port: 8445
      targetPort: 8445
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
