apiVersion: v1
kind: Service
metadata:
  name: consolportals-sa-stc-vcp-httpd-service
  labels:
    app: consolportals-sa-stc-vcp
    component: vcp-httpd
spec:
  type: ClusterIP
  selector:
    app: consolportals-sa-stc-vcp
    component: vcp-httpd
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
