---
apiVersion: v1
kind: Service
metadata:
  name: consolportals-sa-stc-vcp-adminportal-service
  labels:
    app: consolportals-sa-stc-vcp
    component: vcp-adminportal
spec:
  type: ClusterIP
  selector:
    app: consolportals-sa-stc-vcp
    component: vcp-adminportal
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: consolportals-sa-stc-vcp-ccportal-service
  labels:
    app: consolportals-sa-stc-vcp
    component: vcp-ccportal
spec:
  type: ClusterIP
  selector:
    app: consolportals-sa-stc-vcp
    component: vcp-ccportal
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: consolportals-sa-stc-vcp-partnerportal-service
  labels:
    app: consolportals-sa-stc-vcp
    component: vcp-partnerportal
spec:
  type: ClusterIP
  selector:
    app: consolportals-sa-stc-vcp
    component: vcp-partnerportal
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
